
spring:
#  静态资源处理
  resources:
    add-mappings: true  #启用默认静态资源处理
    cache:
      cachecontrol:
        max-age: 3600 #缓存响应时间，单位秒
    chain:
      cache: true #资源链启动缓存，默认启动
      enabled: true #启动资源链，默认禁用
      compressed: true  #启动压缩资源（gzip,brotli)解析，默认禁用
      html-application-cache: true  #启用h5应用缓存，默认禁用
    static-locations: classpath:/static/

#  thymeleaf配置
  thymeleaf:
    cache: false #关闭缓存
  datasource:
#    druid:
#      connection-init-sqls: set names utf8mb4
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
#    username: root
#    password: 510510

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 510510
#    连接池
    hikari:
      pool-name: DataHikariPool
      minimum-idle: 1 #最小空闲连接数
      idle-timeout: 180000 #空闲连接最大存活时间，默认600000ms（10分钟）
      maximum-pool-size: 2 #最大连接数 ，默认10
      auto-commit: true #从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间，默认1800000（30min)
      connection-timeout: 30000 #连接超时时间，默认30000ms
      #测试连接是否否用
      connection-test-query: select 1
  redis:
    timeout: 10000 #连接超时时间
    host:  127.0.0.1 #服务器地址
    port: 6379 #端口号
    database: 1 #数据库
    password: 123456dzx
    lettuce:
      pool:
        max-active: 100 #最大连接数，默认8
        max-wait: 10000ms #最大连接阻塞等待时间，默认-1
        max-idle: 10 #最大空闲连接，默认8
        min-idle: 2 #最小空闲连接，默认0
#        rabbitmq
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: / #虚拟主机
    port: 5672
    listener:
      simple:
        concurrency: 5 #消费者最小数量
        max-concurrency: 10
        prefetch: 1 #限制消费者每次只能处理一条消息
        auto-startup: true  #启动容器，默认true
        default-requeue-rejected: true  #被拒绝时是否重新进入队列
    template:
      retry:
        enabled: true #发布重试，默认false
        initial-interval: 1000ms #重试时间，默认1000
        max-attempts: 3 #重试最大间隔时间
        max-interval: 10000ms #重试最大时间间隔
        multiplier: 2 #重试的间隔乘数，第一次10，第二次10*2，第三次20*2；

#mybatis-plus配置
mybatis-plus:
  # Mappper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 别名
  type-aliases-package: com.dzx.seckill.persistence.bean

#mybatis sql打印（方法接口所在包，不是Mapper.xml所在包)
logging:
  level:
    com.dzx.seckill.persistence.mapper: debug
